 const TeamsAPI=[{name:"Arizona Cardinals",logo:""},
  {name:"Atlanta Falcons",logo:""},
  {name:"Baltimore Ravens",logo:""},
  {name:"Buffalo Bills",logo:""},
  {name:"Carolina Panthers",logo:""},
  {name:"Chicago Bears",logo:""},
  {name:"Cincinnati Bengals",logo:""},
  {name:"Cleveland Browns",logo:""},
  {name:"Dallas Cowboys",logo:""},
  {name:"Denver Broncos",logo:""},
  {name:"Detroit Lions",logo:""},
  {name:"Green Bay Packers",logo:""},
  {name:"Houston Texans",logo:""},
  {name:"Indianapolis Colts",logo:""},
  {name:"Jacksonville Jaguars",logo:""},
  {name:"Kansas City Chiefs",logo:""},
  {name:"Las Vegas Raiders",logo:""},
  {name:"Los Angeles Chargers",logo:""},
  {name:"Los Angeles Rams",logo:""},
  {name:"Miami Dolphins",logo:""},
  {name:"Minnesota Vikings",logo:""},
  {name:"New England Patriots",logo:""},
  {name:"New Orleans Saints",logo:""},
  {name:"New York Giants",logo:""},
  {name:"New York Jets",logo:""},
  {name:"Philadelphia Eagles",logo:""},
  {name:"Pittsburgh Steelers",logo:""},
  {name:"San Francisco 49ers",logo:""},
  {name:"Seattle Seahawks",logo:""},
  {name:"Tampa Bay Buccaneers",logo:""},
  {name:"Tennessee Titans",logo:""},
  {name:"Washington Commanders",logo:""}
  ];

 export default TeamsAPI;