 const TeamsAPI=[
    {name:"Arizona Cardinals",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/ari.png", primaryColor:"#97233F", secondaryColor:"#000000", headCoach:"Vacant", offCoord:"Vacant", defCoord:"Nick Rallis"},
    {name:"Atlanta Falcons",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/atl.png", primaryColor:"#A71930", secondaryColor:"#000000", headCoach:"Kevin Stefanski", offCoord:"Tommy Rees", defCoord:"Jeff Ulbrich"},
    {name:"Baltimore Ravens",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/bal.png", primaryColor:"#241773", secondaryColor:"#000000", headCoach:"Jesse Minter", offCoord:"Declan Doyle", defCoord:"TBD"},
    {name:"Buffalo Bills",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/buf.png", primaryColor:"#00338D", secondaryColor:"#C60C30", headCoach:"Joe Brady", offCoord:"Pete Carmichael", defCoord:"Jim Leonhard"},
    {name:"Carolina Panthers",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/car.png", primaryColor:"#0085CA", secondaryColor:"#101820", headCoach:"Dave Canales", offCoord:"Brad Idzik", defCoord:"Ejiro Evero"},
    {name:"Chicago Bears",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/chi.png", primaryColor:"#0B162A", secondaryColor:"#C83803", headCoach:"Ben Johnson", offCoord:"Vacant", defCoord:"Dennis Allen"},
    {name:"Cincinnati Bengals",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/cin.png", primaryColor:"#FB4F14", secondaryColor:"#000000", headCoach:"Zac Taylor", offCoord:"Dan Pitcher", defCoord:"Al Golden"},
    {name:"Cleveland Browns",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/cle.png", primaryColor:"#311D00", secondaryColor:"#FF3C00", headCoach:"Todd Monken", offCoord:"Travis Switzer", defCoord:"TBD"},
    {name:"Dallas Cowboys",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/dal.png", primaryColor:"#003594", secondaryColor:"#041E42", headCoach:"Brian Schottenheimer", offCoord:"Klayton Adams", defCoord:"TBD"},
    {name:"Denver Broncos",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/den.png", primaryColor:"#FB4F14", secondaryColor:"#002244", headCoach:"Sean Payton", offCoord:"Vacant", defCoord:"TBD"},
    {name:"Detroit Lions",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/det.png", primaryColor:"#0076B6", secondaryColor:"#B0B7BC", headCoach:"Dan Campbell", offCoord:"Drew Petzing", defCoord:"Kelvin Sheppard"},
    {name:"Green Bay Packers",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/gb.png", primaryColor:"#203731", secondaryColor:"#FFB612", headCoach:"Matt LaFleur", offCoord:"Adam Stenavich", defCoord:"TBD"},
    {name:"Houston Texans",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/hou.png", primaryColor:"#03202F", secondaryColor:"#A71930", headCoach:"DeMeco Ryans", offCoord:"Nick Caley", defCoord:"TBD"},
    {name:"Indianapolis Colts",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/ind.png", primaryColor:"#002C5F", secondaryColor:"#A2AAAD", headCoach:"Shane Steichen", offCoord:"Jim Bob Cooter", defCoord:"Lou Anarumo"},
    {name:"Jacksonville Jaguars",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/jax.png", primaryColor:"#101820", secondaryColor:"#D7A22A", headCoach:"Liam Coen", offCoord:"Grant Udinski", defCoord:"Anthony Campanile"},
    {name:"Kansas City Chiefs",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", primaryColor:"#E31837", secondaryColor:"#FFB81C", headCoach:"Andy Reid", offCoord:"Eric Bieniemy", defCoord:"Steve Spagnuolo"},
    {name:"Las Vegas Raiders",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/lv.png", primaryColor:"#000000", secondaryColor:"#A5ACAF", headCoach:"Vacant", offCoord:"Greg Olson", defCoord:"TBD"},
    {name:"Los Angeles Chargers",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/lac.png", primaryColor:"#0080C6", secondaryColor:"#FFC20E", headCoach:"Jim Harbaugh", offCoord:"Mike McDaniel", defCoord:"TBD"},
    {name:"Los Angeles Rams",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png", primaryColor:"#003594", secondaryColor:"#FFA300", headCoach:"Sean McVay", offCoord:"Mike LaFleur", defCoord:"Chris Shula"},
    {name:"Miami Dolphins",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/mia.png", primaryColor:"#008E97", secondaryColor:"#FC4C02", headCoach:"Jeff Hafley", offCoord:"Bobby Slowik", defCoord:"TBD"},
    {name:"Minnesota Vikings",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/min.png", primaryColor:"#4F2683", secondaryColor:"#FFC62F", headCoach:"Kevin O'Connell", offCoord:"Wes Phillips", defCoord:"TBD"},
    {name:"New England Patriots",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/ne.png", primaryColor:"#002244", secondaryColor:"#C60C30", headCoach:"Mike Vrabel", offCoord:"TBD", defCoord:"TBD"},
    {name:"New Orleans Saints",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/no.png", primaryColor:"#D3BC8D", secondaryColor:"#101820", headCoach:"Kellen Moore", offCoord:"Doug Nussmeier", defCoord:"Brandon Staley"},
    {name:"New York Giants",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png", primaryColor:"#0B2265", secondaryColor:"#A71930", headCoach:"John Harbaugh", offCoord:"TBD", defCoord:"Dennard Wilson"},
    {name:"New York Jets",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png", primaryColor:"#125740", secondaryColor:"#000000", headCoach:"Aaron Glenn", offCoord:"Vacant", defCoord:"TBD"},
    {name:"Philadelphia Eagles",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/phi.png", primaryColor:"#004C54", secondaryColor:"#A5ACAF", headCoach:"Nick Sirianni", offCoord:"Kellen Moore", defCoord:"Vic Fangio"},
    {name:"Pittsburgh Steelers",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/pit.png", primaryColor:"#FFB612", secondaryColor:"#101820", headCoach:"Mike McCarthy", offCoord:"Vacant", defCoord:"Patrick Graham"},
    {name:"San Francisco 49ers",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/sf.png", primaryColor:"#AA0000", secondaryColor:"#B3995D", headCoach:"Kyle Shanahan", offCoord:"Klay Kubiak", defCoord:"Gus Bradley"},
    {name:"Seattle Seahawks",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/sea.png", primaryColor:"#002244", secondaryColor:"#69BE28", headCoach:"TBD", offCoord:"TBD", defCoord:"TBD"},
    {name:"Tampa Bay Buccaneers",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/tb.png", primaryColor:"#D50A0A", secondaryColor:"#FF7900", headCoach:"TBD", offCoord:"TBD", defCoord:"TBD"},
    {name:"Tennessee Titans",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/ten.png", primaryColor:"#0C2340", secondaryColor:"#4B92DB", headCoach:"Robert Saleh", offCoord:"Brian Daboll", defCoord:"TBD"},
    {name:"Washington Commanders",logo:"https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png", primaryColor:"#5A1414", secondaryColor:"#FFB612", headCoach:"TBD", offCoord:"TBD", defCoord:"TBD"}
  ];

 export default TeamsAPI;